from enum import StrEnum


class AssistanceLevel(StrEnum):
    INDEPENDENT_RETRY = "L0"
    METACOGNITIVE_PROMPT = "L1"
    CONCEPTUAL_HINT = "L2"
    TARGETED_HINT = "L3"
    GUIDED_STEPS = "L4"
    SIMILAR_WORKED_EXAMPLE = "L5"
    FULL_EXPLANATION = "L6"


class DecisionReasonCode(StrEnum):
    """Stable evidence and transition labels for controller auditability."""

    PRE_INTERACTION = "PRE_INTERACTION"
    FIRST_ATTEMPT = "FIRST_ATTEMPT"
    HIGH_MASTERY = "HIGH_MASTERY"
    LOW_MASTERY = "LOW_MASTERY"
    HIGH_SUPPORT_NEED = "HIGH_SUPPORT_NEED"
    LOW_ERROR_SEVERITY = "LOW_ERROR_SEVERITY"
    HIGH_ERROR_SEVERITY = "HIGH_ERROR_SEVERITY"
    REPEATED_DIFFICULTY = "REPEATED_DIFFICULTY"
    PREVIOUS_HINT_EFFECTIVE = "PREVIOUS_HINT_EFFECTIVE"
    PREVIOUS_HINT_INEFFECTIVE = "PREVIOUS_HINT_INEFFECTIVE"
    PREVIOUS_HINT_EFFECTIVENESS_UNKNOWN = "PREVIOUS_HINT_EFFECTIVENESS_UNKNOWN"
    INDEPENDENT_SUCCESS = "INDEPENDENT_SUCCESS"
    SUCCESS_AFTER_ASSISTANCE = "SUCCESS_AFTER_ASSISTANCE"
    ESCALATION_JUSTIFIED = "ESCALATION_JUSTIFIED"
    FADING_JUSTIFIED = "FADING_JUSTIFIED"
    SUPPORT_MAINTAINED = "SUPPORT_MAINTAINED"
    MINIMUM_SUFFICIENT_ASSISTANCE = "MINIMUM_SUFFICIENT_ASSISTANCE"
